FROM python:3.6-alpine

RUN apk update && apk add --virtual build-deps gcc python3-dev musl-dev && \
  apk add postgresql-dev && \
  apk add netcat-openbsd && \
  apk add git && apk add make

WORKDIR /usr/src/app

COPY . /usr/src/app
RUN pip install --upgrade pip
RUN pip install -U setuptools
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["/usr/src/app/entrypoint.sh"]
