FROM node:11.6.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node-modules/ .bin$PATH


COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install react-scripts@2.1.2 -g

ARG REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_USERS_SERVICE_URL http://localhost
ARG REACT_APP_RECIPES_SERVICE_URL
ENV REACT_APP_RECIPES_SERVICE_URL http://localhost

CMD ["npm", "start"]
